
- name: Update apt cache and install Nginx
  apt:
    name: "{{ nginx_svc }}"
    state: latest
    update_cache: yes
  when: ansible_facts["os_family"]=='Debian'   


- name: Copy website files to the server's document root
  template:
    src: index.html
    dest: "{{ nginx_html_dir }}"
  when: ansible_facts["os_family"]=='Debian'  




- name: Apply Nginx template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx  
  when: ansible_facts["os_family"]=='Debian'    



- name: Enable new site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: Restart Nginx
  when: ansible_facts["os_family"]=='Debian'    
